- name: show interface info on Aoscx and Eos devices
  collections:
    - arubanetworks.aoscx
  hosts: network
  tasks:

    - name: Show interface Info on Eos
      eos_command:
        commands:
          - enable
          - show ip interface brief
      when: ansible_network_os == "eos"

    - name: Show Interface info on Aoscx
      aoscx_command:
        commands:
          - show ip interface brief

      when: ansible_network_os == "arubanetworks.aoscx.aoscx"
