---
- name: configure devices using j2 templates
  hosts: network
  become: true
  collections:
    - arubanetworks.aoscx

  vars_files:
    - vars/breakup-data.yml 
  vars:
    eos_ospf_template: j2/eos-ospf.j2
    aoscx_ospf_template: j2/aoscx-ospf.j2
    aoscx_ospf_config: config/aoscx-ospf.cfg
  
  
  tasks:

    - name: configure ospf on EOS
      eos_config:
        src: "{{ eos_ospf_template }}"
        save_when: changed
      when: ansible_network_os == "eos"

    - template:
        src: "{{ aoscx_ospf_template }}"
        dest: "{{ aoscx_ospf_config }}"
      when: ansible_network_os == "arubanetworks.aoscx.aoscx"
    
    - name: configure ospf on aoscx
      aoscx_config:
        src: "{{ aoscx_ospf_config }}"
        save_when: changed        
      when: ansible_network_os == "arubanetworks.aoscx.aoscx"

    # - name: delete tmp for aoscx
    #   file:
    #     path: "{{ aoscx_ospf_config }}"
    #     state: absent
    #   when: ansible_network_os == "arubanetworks.aoscx.aoscx"
