---
- name: set Aoscx device to Ospf passive interface default
  hosts: cs01
  collections:
    - arubanetworks.aoscx
  vars:
    passint_template: j2/aoscx-ospf-passint-def.j2
    passint_cfg: config/aoscx-ospf-passint-def.cfg
  
  tasks:
    - name: generate Cfg file Aoscx
      template:
        src: "{{ passint_template }}"
        dest: "{{ passint_cfg }}"
      
    - name: configure OSPF 1 (process-id 1)
      aoscx_config:
        src: "{{ passint_cfg }}"