---
- name: configure cs01 for expansion
  hosts: cs01
  collections: 
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx 
  vars_files:
    - vars/expansion-data.yml

  tasks:

    - name: label interfaces
      aoscx_interface:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
      loop: "{{ intr_descr[inventory_hostname]}}"

    - name: configure layer3 interface
      aoscx_l3_interface:
        interface: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
      loop: "{{ layer3_data[inventory_hostname] }}"
        
    - name: bring up the outside interface up
      aoscx_interface:
        name: 1/1/4
        enabled: True


