---
- name: Reinit phase
  ansible.builtin.import_playbook: prepare-adjustment/eos-reinitialize-l3.yml

- name: Breakout phase
  ansible.builtin.import_playbook: prepare-adjustment/breakup.yml

- name: OSPF Breakout phase
  ansible.builtin.import_playbook: prepare-adjustment/ospf-breakup.yml

- name: Preparer EBGP
  ansible.builtin.import_playbook: prepare-adjustment/ospf-passint-def.yml

- name: EBGP Breakout phase
  ansible.builtin.import_playbook: prepare-adjustment/ebgp-breakup.yml

- name: Adjustment phase
  ansible.builtin.import_playbook: prepare-adjustment/adjustment.yml
