---
- name: create users on the spine machines
  hosts: spines
  become: true
  vars_files:
    - vars/users-secret.yml

  tasks:
    - name: create users
      eos_user:
        name: "{{ item.name }}"
        configured_password: "{{ item.pw }}"
        state: present
      loop: "{{ newusers }}"
      loop_control:
        label: "{{ item.name }}"
