---
- name: back up from an Aoscx device
  hosts: cs01
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
    dest: 172.16.5.1
  gather_facts: False
  tasks:
    - name: "test reachability from target to destination"
      aoscx_command:
        commands: ['ping {{dest}}']
      register: ping_response
    - debug:
        var: ping_response.stdout
