---
- name: consolidate EOS layer 3 network
  hosts: network
  become: true
  vars_files:
    - vars/consolidation-data.yml

  tasks:

    - name: configure interface descriptions
      debug: 
        msg: "{{ item }}"
      with_dict: "{{ interface_data[inventory_hostname] }}"

    - name: configure interface descriptions
      eos_interfaces:
        config: 
          - name: "{{ item.key }}"
            description: "{{ item.value.description }}"
      with_dict: "{{ interface_data[inventory_hostname] }}"
      when: ansible_network_os == "eos"

    - name: configure layer 3
      eos_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ipv4 }}"
      loop: "{{ layer3_data[inventory_hostname] }}"
      when: ansible_network_os == "eos"


- name: consolidate AOSCX layer 3 network
  hosts: network
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
  vars_files:
    - vars/consolidation-data.yml
  
  tasks:
    - name: configure interface descriptions
      aoscx_interface:
          name: "{{ item.key }}"
          description: "{{ item.value.description }}"
      with_dict: "{{ interface_data[inventory_hostname] }}"
      when: ansible_network_os == "arubanetworks.aoscx.aoscx"

    - name: configure layer 3
      aoscx_l3_interface:
          interface: "{{ item.name }}"
          ipv4:
              - "{{ item.ipv4 }}"
      loop: "{{ layer3_data[inventory_hostname] }}"
      when: ansible_network_os == "arubanetworks.aoscx.aoscx"
    

    
