---
- name: Test jinja2 template for aoscx 
  hosts: network
  vars:
    ansible_connection: local
    template_file: j2/aoscx-hn-dn-ns.j2
    cfg_file: config/aoscx-hn-dn-ns.cfg

  tasks:

    - name: create config if not exists already
      file:
        path: config/
        state: directory

    - name: template cfg file
      template:
        src: "{{ template_file }}"
        dest: "{{ cfg_file }}"
